apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-server"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: "{{ .Chart.Name }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: ANTI_CHEAT_TYPE21
          value: "{{ .Values.env.antiCheatType21 }}"
        - name: ADMIN_PASSWORD
          value: "{{ .Values.env.adminPassword }}"
        - name: ADMIN_USERNAME
          value: "{{ .Values.env.adminUsername }}"
        - name: AUTOSAVE_INTERVAL
          value: "{{ .Values.env.autosaveInterval }}"
        - name: BACKUPS_COUNT
          value: "{{ .Values.env.backupsCount  }}"
        - name: BACKUPS_PERIOD
          value: "{{ .Values.env.backupsPeriod }}"
        - name: BETA_BRANCH
          value: "{{ .Values.env.betaBranch }}"
        - name: DIRECT_PORT
          value: "{{ .Values.env.queryPort }}"
        - name: GAME_PORT
          value: "{{ .Values.env.gamePort }}"
        - name: MAP_NAMES
          value: "{{ .Values.env.mapNames }}"
        - name: MAX_MEMORY
          value: "{{ .Values.env.maxRAM }}"
        - name: MAX_PLAYERS
          value: "{{ .Values.env.maxPlayers }}"
        - name: MOD_IDS
          value: "{{ .Values.env.modWorkshopIDs }}"
        - name: MOD_NAMES
          value: "{{ .Values.env.modNames }}"
        - name: PAUSE_EMPTY
          value: "{{ .Values.env.pauseOnEmpty }}"
        - name: PING_LIMIT
          value: "{{ .Values.env.pingLimit }}"
        - name: PVP
          value: "{{ .Values.env.pvp }}"
        - name: PUBLIC
          value: "{{ .Values.env.public }}"
        - name: RCON_PASSWORD
          value: "{{ .Values.env.rconPassword }}"
        - name: RCON_PORT
          value: "{{ .Values.env.rconPort }}"
        - name: SERVER_IP
          value: "{{ .Values.env.serverIP }}"
        - name: SERVER_NAME
          value: "{{ .Values.env.serverName }}"
        - name: SERVER_PASSWORD
          value: "{{ .Values.env.serverPassword }}"
        - name: STEAM_VAC
          value: "{{ .Values.env.steamVAC }}"
        ports:
        - name: game-port
          containerPort: {{ .Values.env.gamePort | int }}
          hostIP: {{ .Values.env.hostIP }}
          hostPort: {{ .Values.env.gamePort | int }}
          protocol: UDP
        - name: query-port
          containerPort: {{ .Values.env.queryPort | int }}
          hostIP: {{ .Values.env.hostIP }}
          hostPort: {{ .Values.env.queryPort | int }}
          protocol: UDP
        - name: rcon-port
          containerPort: {{ .Values.env.rconPort | int }}
          hostIP: {{ .Values.env.hostIP }}
          hostPort: {{ .Values.env.rconPort | int }}
          protocol: TCP
        volumeMounts:
        - name: zomboid-data
          mountPath: /home/steam/ZomboidDedicatedServer
        - name: zomboid-config
          mountPath: /home/steam/Zomboid
      volumes:
      - name: zomboid-data
        persistentVolumeClaim:
          claimName: "{{ .Chart.Name }}-pvc-data"
      - name: zomboid-config
        persistentVolumeClaim:
          claimName: "{{ .Chart.Name }}-pvc-config"
      hostNetwork: {{ .Values.service.hostNetwork }}
